'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Bus_Reservation.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property add_property_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_property-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property advance_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("advance-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancelled_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancelled_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property checklist_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checklist-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chevron_left_round_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chevron_left_round-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property chevron_right_round_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chevron_right_round-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete_property_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete_property-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property edit_property_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_property-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property end_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("end-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property process_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("process-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property return_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("return-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rupee_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rupee-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search_property_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_property-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property seat_layout_screen_nor_avl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seat_layout_screen_nor_avl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property seat_layout_screen_nor_avl1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seat_layout_screen_nor_avl1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property seat_layout_tab_nor_lad_avl_rotated() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seat_layout_tab_nor_lad_avl_rotated", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shutdown_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shutdown-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stairs_down_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stairs_down-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stairs_up_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stairs_up-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property start_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("start-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property steering_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("steering_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property travel_bus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("travel_bus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property xbox_menu_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("xbox_menu-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
